spring.application.name=check-in-service
app.checkedin.event=checkedin-event
app.legacy.baseUrl=https://system.siemensemployeerecord.de

#database config
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5
spring.datasource.url=jdbc:postgresql://localhost:5432/checkin_db
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=
spring.datasource.password=

#jpa config
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

#h2-console
spring.h2.console.enabled=true

#to remove
spring.sql.init.mode=always

#kafka config
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=kafkacheckinevent
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.admin.auto-create=true
spring.kafka.listener.missing-topics-fatal=false

#mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#circuit-breaker
resilience4j.circuitbreaker.instances.legacy.sliding-window-size=100
resilience4j.circuitbreaker.instances.legacy.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.legacy.wait-duration-in-open-state=30s

#rate-limiter
resilience4j.ratelimiter.instances.legacy.limit-for-period=10
resilience4j.ratelimiter.instances.legacy.limit-refresh-period=1s

#retry
resilience4j.retry.instances.legacy.max-attempts=3
resilience4j.retry.instances.legacy.wait-duration=500ms
